# Generated by Django 6.0.2 on 2026-02-07 21:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plainte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid_public",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("plaignant_nom", models.CharField(max_length=255)),
                (
                    "plaignant_contact",
                    models.CharField(help_text="Email ou Téléphone", max_length=100),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("PENAL", "Affaire Pénale (Vol, Agression...)"),
                            ("CIVIL", "Affaire Civile (Divorce, Foncier...)"),
                            ("ADMIN", "Administratif (État civil, Urbanisme)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("objet", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("est_cloture", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PieceJointe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fichier", models.FileField(upload_to="pieces_jointes/%Y/%m/")),
                ("description", models.CharField(max_length=100)),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "plainte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces",
                        to="dossiers.plainte",
                    ),
                ),
            ],
        ),
    ]
