# Generated by Django 6.0.2 on 2026-02-10 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceConviction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la pièce')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('type_piece', models.CharField(choices=[('NUMERIQUE', 'Fichier Numérique (PDF, Image, Audio)'), ('PHYSIQUE', 'Objet Physique / Matériel (Scellé)')], default='NUMERIQUE', max_length=20)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='preuves/%Y/%m/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('plainte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='dossiers.plainte')),
            ],
        ),
        migrations.DeleteModel(
            name='PieceJointe',
        ),
    ]
