# Generated by Django 6.0.2 on 2026-02-07 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dossiers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EtapeProcessus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_etape",
                    models.CharField(
                        choices=[
                            ("DEPOT", "Dépôt de la plainte"),
                            ("RECEVABILITE", "Examen de recevabilité"),
                            ("ENQUETE", "Enquête / Instruction en cours"),
                            ("AUDIENCE", "Audience fixée"),
                            ("DELIBERE", "Mise en délibéré"),
                            ("JUGEMENT", "Jugement rendu / Résolution"),
                            ("CLOTURE", "Dossier archivé"),
                            ("REJET", "Dossier rejeté / Classé sans suite"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_traitement", models.DateTimeField(auto_now_add=True)),
                (
                    "commentaire_interne",
                    models.TextField(
                        blank=True, help_text="Visible seulement par les employés"
                    ),
                ),
                (
                    "message_public",
                    models.TextField(
                        blank=True,
                        help_text="Ce qui apparaitra sur le graphe du citoyen",
                    ),
                ),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "etape_precedente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workflow.etapeprocessus",
                    ),
                ),
                (
                    "plainte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="dossiers.plainte",
                    ),
                ),
            ],
            options={
                "ordering": ["date_traitement"],
            },
        ),
    ]
