# Generated by Django 6.0.2 on 2026-02-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapeprocessus',
            name='document_joint',
            field=models.FileField(blank=True, null=True, upload_to='procedure_actes/%Y/%m/', verbose_name='Acte / Jugement / Notification (PDF/Image)'),
        ),
    ]
